In [9]:
import numpy as np

In [10]:
a=np.array([1,2,3,6,4,5])
rev_a=a[::-1]
print(rev_a)

[5 4 6 3 2 1]


In [11]:
b=np.array([[1,2,3],[2,4,5],[1,2,3]])
b_flatten=b.flatten()
print(b_flatten)

[1 2 3 2 4 5 1 2 3]


In [12]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
print(arr1==arr2)


[[ True  True]
 [ True  True]]


In [16]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
np.bincount(x).argmax()

#for y
valy,cnty=np.unique(y,return_counts=True)
most_y=valy[np.argmax(cnty)]
print(most_y)
index=np.where(y==most_y)
print(index)

1
(array([0, 1, 2]),)


In [14]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
sum_gfg=np.sum(gfg)
print(sum_gfg)
row_sum=np.sum(gfg,1)
col_sum=np.sum(gfg,0)
print(row_sum)
print(col_sum)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [17]:
n_arr=np.array([[55,25,15],[30,44,2],[11,45,77]])
sum_diag=np.trace(n_arr)
print(sum_diag)
eigenval,eigenvec=np.linalg.eig(n_arr)
print(eigenval)
print(eigenvec)
inv=np.linalg.inv(n_arr)
inv
det=np.linalg.det(n_arr)
det

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


np.float64(137180.0000000001)

In [18]:
p1=np.array([[1,2],[2,3]])
q1=np.array([[4,5],[6,7]])
p2=np.array([[1,2],[2,3],[4,5]])
q2=np.array([[4,5,1],[6,7,2]])
np.dot(p1,q1)
np.dot(p2,q2)

cov1=np.cov(p1.flatten(),q1.flatten())
print(cov1)
cov2=np.cov(p2.flatten(),q2.flatten())
cov2


[[0.66666667 1.        ]
 [1.         1.66666667]]


array([[2.16666667, 0.23333333],
       [0.23333333, 5.36666667]])

In [24]:
h=np.array([[2,3,4],[3,2,9]])
j=np.array([[1,5,0],[5,10,3]])
inner=np.inner(h,j)
print(inner)
outer=np.outer(h.flatten(),j.flatten())
print(outer)
cp=np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
cp


[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 2],
       [1, 4],
       [1, 3],
       [1, 3],
       [2, 1],
       [2, 1],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [2, 2],
       [2, 4],
       [2, 3],
       [2, 3],
       [3, 1],
       [3, 1],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4],
       [3, 2],
       [3, 4],
       [3, 3],
       [3, 3],
       [4, 1],
       [4, 1],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4],
       [4, 2],
       [4, 4],
       [4, 3],
       [4, 3],
       [5, 1],
       [5, 1],
       [5, 1],
       [5, 2],
       [5, 3],
       [5, 4],
       [5, 2],
       [5, 4],
       [5, 3],
       [5, 3],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 2],
       [1, 4],
       [1, 3],
       [1, 3],
       [2, 1],
       [2, 1],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [2,

In [25]:
array = np.array([[1,-2,3],[-4,5,-6]])
abs_arr=np.abs(array)
print(abs_arr)
perc=np.percentile(array.flatten(),[25,50,75])
print(perc)
perc_row=np.percentile(array,[25,50,75],axis=0)
print(perc_row)
perc_col=np.percentile(array,[25,50,75],axis=1)
print(perc_col)

[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [27]:
mean_f=np.mean(array.flatten())
median=np.median(array.flatten())
std=np.std(array.flatten())

mean_c=np.mean(array,axis=0)
median_c=np.median(array,axis=0)
std_c=np.std(array,axis=0)

In [28]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor=np.floor(a)
ceil=np.ceil(a)
trun=np.trunc(a)
round=np.round(a)
floor,ceil,trun,round

(array([-2., -2., -1.,  0.,  1.,  1.,  3.]),
 array([-1., -1., -0.,  1.,  2.,  2.,  3.]),
 array([-1., -1., -0.,  0.,  1.,  1.,  3.]),
 array([-2., -2., -0.,  0.,  2.,  2.,  3.]))

In [29]:
arr1=np.array([10,52,62,16,16,54,453])
sort=np.sort(arr1)
sort_index=np.argsort(arr1)
small=np.sort(arr1)[:4]
large=np.sort(array)[-5:]
sort,sort_index,small,large

(array([ 10,  16,  16,  52,  54,  62, 453]),
 array([0, 3, 4, 1, 5, 2, 6]),
 array([10, 16, 16, 52]),
 array([[-2,  1,  3],
        [-6, -4,  5]]))

In [32]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers=array[array==array.astype(int)]
floats=array[array!=array.astype(int)]

integers,floats


(array([1., 2., 3., 2.]), array([1.2, 2.2]))